<?php
  //CONFIGURACION DEL SERVIDOR Y LA BASE DE DATOS
  $SERVIDOR = "localhost:8889";
  $USER = "root";
  $PASS = "root";
  $BD = "SIE";
  $ALUMNOS = "ALUMNOS";
  $EXAMENES_DIAGNOSTICO = "EXAMENES_DIAGNOSTICO";
  $ACREDITACIONES = "ACREDITACIONES";
?>
